/**
 * 기본 목업 게시물 데이터
 * - 실제 업로드 데이터(`uploadedPosts`)가 없어도 메인/피드 화면이 비어 보이지 않도록 사용
 * - 구조는 `UploadScreen`에서 저장하는 로컬 게시물 형식을 최대한 맞춤
 */

const now = Date.now();
const hoursAgo = (h) => new Date(now - h * 60 * 60 * 1000).toISOString();

export const MOCK_POSTS = [
  {
    id: 'mock-1',
    userId: 'mock-user-1',
    user: '서울라이프',
    images: [
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    ],
    videos: [],
    imageCount: 1,
    videoCount: 0,
    location: '서울 강남역',
    detailedLocation: '서울 강남역 11번 출구 앞 카페 거리',
    placeName: '강남역 카페거리',
    region: '서울',
    tags: ['#맑음', '#퇴근길', '#카페거리'],
    note: '퇴근하고 잠깐 들른 강남역 카페 거리, 사람들로 북적북적해요.',
    timestamp: new Date(hoursAgo(1)).getTime(),
    createdAt: hoursAgo(1),
    photoDate: hoursAgo(2),
    timeLabel: '1시간 전',
    likes: 128,
    isNew: true,
    isLocal: false,
    category: 'scenic',
    categoryName: '추천 장소',
    coordinates: { lat: 37.4979, lng: 127.0276 },
    weather: {
      icon: '☀️',
      condition: '맑음',
      temperature: '22℃',
      fetchedAt: now,
    },
    exifData: null,
    verifiedLocation: '서울 강남구 강남대로 396',
    thumbnail: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
  },
  {
    id: 'mock-2',
    userId: 'mock-user-2',
    user: '해운대러버',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    ],
    videos: [],
    imageCount: 1,
    videoCount: 0,
    location: '부산 해운대',
    detailedLocation: '부산 해운대해수욕장',
    placeName: '해운대해수욕장',
    region: '부산',
    tags: ['#여름날씨', '#바다', '#해운대'],
    note: '파도 소리 들으면서 걷기 딱 좋은 저녁 시간.',
    timestamp: new Date(hoursAgo(3)).getTime(),
    createdAt: hoursAgo(3),
    photoDate: hoursAgo(4),
    timeLabel: '3시간 전',
    likes: 96,
    isNew: true,
    isLocal: false,
    category: 'scenic',
    categoryName: '추천 장소',
    coordinates: { lat: 35.1587, lng: 129.1604 },
    weather: {
      icon: '🌤️',
      condition: '구름 조금',
      temperature: '24℃',
      fetchedAt: now,
    },
    exifData: null,
    verifiedLocation: '부산 해운대구 우동',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    user: '제주살이',
    images: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
    ],
    videos: [],
    imageCount: 1,
    videoCount: 0,
    location: '제주 애월',
    detailedLocation: '제주 애월 바닷가 카페',
    placeName: '애월 카페거리',
    region: '제주',
    tags: ['#여름날씨', '#카페', '#오션뷰'],
    note: '창밖으로 바다가 보이는 애월 카페, 조용히 책 읽기 좋아요.',
    timestamp: new Date(hoursAgo(5)).getTime(),
    createdAt: hoursAgo(5),
    photoDate: hoursAgo(6),
    timeLabel: '5시간 전',
    likes: 73,
    isNew: true,
    isLocal: false,
    category: 'scenic',
    categoryName: '추천 장소',
    coordinates: { lat: 33.4618, lng: 126.3092 },
    weather: {
      icon: '🌤️',
      condition: '바람 약간',
      temperature: '23℃',
      fetchedAt: now,
    },
    exifData: null,
    verifiedLocation: '제주 제주시 애월읍',
    thumbnail: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
  },
  {
    id: 'mock-4',
    userId: 'mock-user-4',
    user: '야경러버',
    images: [
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
    ],
    videos: [],
    imageCount: 1,
    videoCount: 0,
    location: '서울 한강공원',
    detailedLocation: '서울 반포 한강공원 달빛무지개분수',
    placeName: '반포 한강공원',
    region: '서울',
    tags: ['#야경', '#한강', '#피크닉'],
    note: '분수 쇼 시작하기 직전, 돗자리 깔고 야식 준비 완료!',
    timestamp: new Date(hoursAgo(10)).getTime(),
    createdAt: hoursAgo(10),
    photoDate: hoursAgo(11),
    timeLabel: '10시간 전',
    likes: 154,
    isNew: false,
    isLocal: false,
    category: 'nightview',
    categoryName: '야경 명소',
    coordinates: { lat: 37.5087, lng: 126.9920 },
    weather: {
      icon: '🌙',
      condition: '맑은 밤',
      temperature: '18℃',
      fetchedAt: now,
    },
    exifData: null,
    verifiedLocation: '서울 서초구 반포동',
    thumbnail: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
  },
  {
    id: 'mock-5',
    userId: 'mock-user-5',
    user: '벚꽃러버',
    images: [
      'https://images.unsplash.com/photo-1492496913980-501348b61469?w=800&q=80',
    ],
    videos: [],
    imageCount: 1,
    videoCount: 0,
    location: '전주 한옥마을',
    detailedLocation: '전주 한옥마을 골목길',
    placeName: '전주 한옥마을',
    region: '전주',
    tags: ['#벚꽃', '#한옥마을', '#산책'],
    note: '골목마다 벚꽃이 흩날려서 사진 찍기 좋은 시즌.',
    timestamp: new Date(hoursAgo(20)).getTime(),
    createdAt: hoursAgo(20),
    photoDate: hoursAgo(24),
    timeLabel: '20시간 전',
    likes: 61,
    isNew: false,
    isLocal: false,
    category: 'season',
    categoryName: '시즌 스팟',
    coordinates: { lat: 35.8156, lng: 127.1530 },
    weather: {
      icon: '☀️',
      condition: '봄날씨',
      temperature: '19℃',
      fetchedAt: now,
    },
    exifData: null,
    verifiedLocation: '전북 전주시 완산구 기린대로',
    thumbnail: 'https://images.unsplash.com/photo-1492496913980-501348b61469?w=800&q=80',
  },
  {
    id: 'mock-6',
    userId: 'mock-user-6',
    user: '카페탐방러',
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    ],
    videos: [],
    imageCount: 1,
    videoCount: 0,
    location: '성수동 카페거리',
    detailedLocation: '서울 성수동 로스터리 카페',
    placeName: '성수 핫플 카페',
    region: '서울',
    tags: ['#신메뉴', '#카페', '#성수동'],
    note: '오늘부터 한정 판매라는 신메뉴 라떼, 생각보다 훨씬 맛있어요.',
    timestamp: new Date(hoursAgo(8)).getTime(),
    createdAt: hoursAgo(8),
    photoDate: hoursAgo(9),
    timeLabel: '8시간 전',
    likes: 89,
    isNew: true,
    isLocal: false,
    category: 'food',
    categoryName: '맛집',
    coordinates: { lat: 37.5446, lng: 127.0559 },
    weather: {
      icon: '⛅',
      condition: '구름 조금',
      temperature: '21℃',
      fetchedAt: now,
    },
    exifData: null,
    verifiedLocation: '서울 성동구 성수동',
    thumbnail: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
  },
];

export const getCombinedPosts = (localPosts = []) => {
  const safeLocalPosts = Array.isArray(localPosts) ? localPosts : [];
  // 로컬 업로드 게시물을 우선으로 보여주고, 그 뒤에 목업 데이터를 붙임
  return [...safeLocalPosts, ...MOCK_POSTS];
};

