// 추천 여행지용 목업 데이터
// - 메인 화면 추천 섹션 / Supabase 연동 전 테스트용
// - 설명, 사진, 해시태그가 서로 맥락이 맞도록 구성

export const MOCK_RECOMMENDED_POSTS = [
  {
    id: 'rec-001',
    region: '서울',
    location: '서울 성수동',
    placeName: '성수 카페거리',
    title: '성수 브런치 카페 골목 산책',
    description: '로스터리 카페와 편집숍이 모여 있는 성수 카페 골목. 주말 오전 브런치와 가벼운 산책 코스로 좋아요.',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    hashtags: ['#서울', '#성수동', '#카페거리', '#브런치', '#산책코스'],
  },
  {
    id: 'rec-002',
    region: '서울',
    location: '서울 연남동',
    placeName: '연남동 동네 산책',
    title: '연트럴파크 피크닉 & 카페투어',
    description: '경의선숲길을 따라 잔디 위에 돗자리 펴고, 골목 안 카페들까지 한 번에 즐기는 연남동 데이트 코스.',
    image: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80',
    hashtags: ['#서울', '#연남동', '#연트럴파크', '#피크닉', '#데이트코스'],
  },
  {
    id: 'rec-003',
    region: '서울',
    location: '서울 한강공원',
    placeName: '반포 한강공원',
    title: '반포대교 분수 야경 피크닉',
    description: '달빛무지개분수와 함께 야경 감상하기 좋은 반포 한강공원. 치맥과 돗자리만 준비하면 완성되는 밤 산책 코스.',
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
    hashtags: ['#서울야경', '#한강공원', '#반포대교', '#피크닉', '#치맥'],
  },
  {
    id: 'rec-004',
    region: '서울',
    location: '서울 북촌',
    placeName: '북촌 한옥마을',
    title: '골목마다 사진 스팟, 북촌 한옥마을',
    description: '전통 한옥 지붕 사이로 보이는 도심 풍경. 조용한 골목을 따라 걷다 보면 자연스럽게 사진이 쌓여요.',
    image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80',
    hashtags: ['#서울', '#북촌한옥마을', '#골목산책', '#사진스팟', '#한옥'],
  },
  {
    id: 'rec-005',
    region: '서울',
    location: '서울 익선동',
    placeName: '익선동 한옥골목',
    title: '익선동 레트로 한옥 카페 투어',
    description: '한옥을 개조한 레트로 카페와 식당이 모여 있는 익선동. 저녁 조명 켜질 때쯤 걸으면 분위기가 최고예요.',
    image: 'https://images.unsplash.com/photo-1549692520-acc6669e2f0c?w=800&q=80',
    hashtags: ['#서울', '#익선동', '#레트로감성', '#한옥카페', '#야간산책'],
  },
  {
    id: 'rec-006',
    region: '부산',
    location: '부산 해운대',
    placeName: '해운대 해수욕장',
    title: '해운대 해변 산책과 노을 구경',
    description: '부산을 대표하는 해수욕장. 해 질 무렵 산책로를 따라 걸으며 노을과 파도 소리를 함께 즐길 수 있어요.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    hashtags: ['#부산', '#해운대', '#바다여행', '#노을맛집', '#해변산책'],
  },
  {
    id: 'rec-007',
    region: '부산',
    location: '부산 광안리',
    placeName: '광안리 해수욕장',
    title: '광안대교 야경과 카페 라운지',
    description: '광안대교 야경을 정면으로 바라보는 카페들이 줄지어 있는 광안리. 밤바다와 네온사인을 함께 담을 수 있는 포토 스팟.',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
    hashtags: ['#부산', '#광안리', '#야경스팟', '#바다카페', '#드라이브코스'],
  },
  {
    id: 'rec-008',
    region: '부산',
    location: '부산 감천동',
    placeName: '감천문화마을',
    title: '알록달록 감천문화마을 전망 산책',
    description: '언덕 위로 다닥다닥 붙은 파스텔 톤 집들이 만들어내는 부산의 대표 포토존. 골목마다 숨은 벽화와 카페를 찾아보세요.',
    image: 'https://images.unsplash.com/photo-1549893075-7e95b0c0d48b?w=800&q=80',
    hashtags: ['#부산', '#감천문화마을', '#전망좋은곳', '#벽화마을', '#포토존'],
  },
  {
    id: 'rec-009',
    region: '부산',
    location: '부산 송정',
    placeName: '송정 서핑 비치',
    title: '송정 서핑 & 해변 라이프',
    description: '부산에서 서핑보드를 가장 많이 볼 수 있는 송정 해변. 파도 타는 사람들 구경하며 카페 창가에 앉아 쉬기 좋아요.',
    image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800&q=80',
    hashtags: ['#부산', '#송정해수욕장', '#서핑', '#바다카페', '#여름여행'],
  },
  {
    id: 'rec-010',
    region: '부산',
    location: '부산 기장',
    placeName: '기장 해안 드라이브',
    title: '기장 해안 절벽 뷰 카페 드라이브',
    description: '절벽 위에 자리 잡은 오션뷰 카페들이 유명한 기장 해안 도로. 드라이브하다가 마음에 드는 카페에 잠시 멈춰보세요.',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80',
    hashtags: ['#부산', '#기장', '#해안도로', '#오션뷰카페', '#드라이브'],
  },
  {
    id: 'rec-011',
    region: '제주',
    location: '제주 애월',
    placeName: '애월 해안 산책로',
    title: '제주 애월 바다 앞 카페 거리',
    description: '푸른 바다와 카페 테라스가 이어지는 애월 해안도로. 잔잔한 파도 소리 들으며 천천히 걷기 좋은 코스입니다.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
    hashtags: ['#제주', '#애월', '#바다산책', '#카페투어', '#드라이브코스'],
  },
  {
    id: 'rec-012',
    region: '제주',
    location: '제주 성산',
    placeName: '성산일출봉',
    title: '성산일출봉 일출 등반',
    description: '해 뜨기 전 어둑한 하늘 아래에서 시작하는 등반. 정상에서 맞이하는 붉은 일출이 여행의 하이라이트가 됩니다.',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    hashtags: ['#제주', '#성산일출봉', '#일출명소', '#새벽등반', '#뷰맛집'],
  },
  {
    id: 'rec-013',
    region: '제주',
    location: '제주 함덕',
    placeName: '함덕 서우봉 해변',
    title: '에메랄드 빛 함덕 해변과 서우봉',
    description: '에메랄드 빛 바다와 잔잔한 파도가 펼쳐지는 함덕해수욕장. 서우봉 언덕에서 내려다보는 뷰가 특히 예쁩니다.',
    image: 'https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800&q=80',
    hashtags: ['#제주', '#함덕해수욕장', '#에메랄드바다', '#서우봉', '#뷰포인트'],
  },
  {
    id: 'rec-014',
    region: '제주',
    location: '제주 서귀포',
    placeName: '쇠소깍',
    title: '쇠소깍 카약과 숲길 산책',
    description: '깊은 에메랄드 물빛과 울창한 숲이 어우러진 쇠소깍. 카약 타고 천천히 강을 거슬러 올라가는 경험이 특별해요.',
    image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800&q=80',
    hashtags: ['#제주', '#쇠소깍', '#카약', '#숲길', '#힐링여행'],
  },
  {
    id: 'rec-015',
    region: '제주',
    location: '제주 한림',
    placeName: '협재해수욕장',
    title: '협재·금능 쪽빛 바다 드라이브',
    description: '하얀 모래와 쪽빛 바다가 이어지는 협재·금능 해변. 인근 오션뷰 카페에서 여유롭게 바다를 감상해 보세요.',
    image: 'https://images.unsplash.com/photo-1526481280695-3c687fd543c0?w=800&q=80',
    hashtags: ['#제주', '#협재해수욕장', '#금능해수욕장', '#드라이브', '#힐링'],
  },
  {
    id: 'rec-016',
    region: '강릉',
    location: '강릉 안목해변',
    placeName: '안목 커피거리',
    title: '강릉 안목 커피거리 모래사장 카페',
    description: '카페 창가 너머로 바로 모래사장이 보이는 안목해변. 파도 소리 들으며 커피 한 잔 마시기 좋은 시간.',
    image: 'https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800&q=80',
    hashtags: ['#강릉', '#안목해변', '#커피거리', '#동해바다', '#당일치기'],
  },
  {
    id: 'rec-017',
    region: '강릉',
    location: '강릉 경포대',
    placeName: '경포호수 & 해변',
    title: '경포호수 산책과 해변 일출',
    description: '호수 둘레길을 따라 산책하고, 이른 아침에는 해변에서 떠오르는 해를 감상할 수 있는 코스.',
    image: 'https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800&q=80',
    hashtags: ['#강릉', '#경포대', '#호수산책', '#일출', '#걷기좋은곳'],
  },
  {
    id: 'rec-018',
    region: '속초',
    location: '속초 해수욕장',
    placeName: '속초 해변 & 영금정',
    title: '속초 해변 산책과 영금정 전망',
    description: '속초해수욕장에서 가볍게 걷다가, 영금정에 올라 동해를 한눈에 내려다보는 루트.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    hashtags: ['#속초', '#속초해수욕장', '#영금정', '#동해여행', '#전망좋은곳'],
  },
  {
    id: 'rec-019',
    region: '속초',
    location: '설악산',
    placeName: '설악산 국립공원',
    title: '케이블카 타고 즐기는 설악산 뷰',
    description: '가벼운 등산 또는 케이블카로도 멋진 산악 뷰를 즐길 수 있는 설악산. 단풍철에는 특히 인기 많은 코스.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=800&q=80',
    hashtags: ['#속초', '#설악산', '#단풍명소', '#케이블카', '#가족여행'],
  },
  {
    id: 'rec-020',
    region: '경주',
    location: '경주 대릉원 일대',
    placeName: '대릉원 & 황리단길',
    title: '대릉원 돌담길과 황리단길 한옥거리',
    description: '고분군 돌담길을 따라 걷다 보면 한옥 카페와 맛집이 모여 있는 황리단길로 자연스럽게 이어지는 코스.',
    image: 'https://images.unsplash.com/photo-1526481280695-3c687fd543c0?w=800&q=80',
    hashtags: ['#경주', '#대릉원', '#황리단길', '#한옥거리', '#역사여행'],
  },
  {
    id: 'rec-021',
    region: '경주',
    location: '경주 보문단지',
    placeName: '보문호수',
    title: '보문호수 자전거 한 바퀴',
    description: '호수 주변 자전거 도로가 잘 정비되어 있어, 가볍게 자전거를 빌려 한 바퀴 돌기 좋은 코스입니다.',
    image: 'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?w=800&q=80',
    hashtags: ['#경주', '#보문호수', '#자전거코스', '#호수뷰', '#가족여행'],
  },
  {
    id: 'rec-022',
    region: '전주',
    location: '전주 한옥마을',
    placeName: '전주 한옥마을',
    title: '한복 입고 걷는 전주 한옥마을',
    description: '골목마다 한복 대여점과 맛집이 가득한 전주 한옥마을. 전주비빔밥과 막걸리 골목까지 한 번에 즐길 수 있어요.',
    image: 'https://images.unsplash.com/photo-1492496913980-501348b61469?w=800&q=80',
    hashtags: ['#전주', '#한옥마을', '#한복체험', '#전주맛집', '#주말여행'],
  },
  {
    id: 'rec-023',
    region: '전주',
    location: '전주 오목대',
    placeName: '오목대 전망대',
    title: '오목대에서 내려다보는 한옥마을 전경',
    description: '언덕 위 오목대 전망대에 오르면 전주 한옥마을 지붕들이 한눈에 들어옵니다. 해 질 녘이 특히 예뻐요.',
    image: 'https://images.unsplash.com/photo-1526481280695-3c687fd543c0?w=800&q=80',
    hashtags: ['#전주', '#오목대', '#전망좋은곳', '#야경', '#사진스팟'],
  },
  {
    id: 'rec-024',
    region: '여수',
    location: '여수 돌산대교',
    placeName: '여수 밤바다',
    title: '여수밤바다 전망과 해산물 거리',
    description: '돌산대교와 오동도 불빛이 어우러지는 여수 밤바다. 낭만포차 거리에서 해산물과 함께 즐기기 좋은 코스입니다.',
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
    hashtags: ['#여수', '#여수밤바다', '#돌산대교', '#해산물맛집', '#야경여행'],
  },
  {
    id: 'rec-025',
    region: '여수',
    location: '여수 향일암',
    placeName: '향일암',
    title: '해돋이 명소, 여수 향일암',
    description: '바다를 마주 보고 서 있는 절벽 위 사찰. 일출 시간에 맞춰 올라가면 태양이 바다에서 떠오르는 장관을 볼 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800&q=80',
    hashtags: ['#여수', '#향일암', '#해돋이', '#절벽뷰', '#일출명소'],
  },
  {
    id: 'rec-026',
    region: '인천',
    location: '인천 을왕리',
    placeName: '을왕리 해수욕장',
    title: '서울 근교 바다, 을왕리 노을',
    description: '서울에서 차로 한 시간 반이면 도착하는 근교 바다. 노을 질 때 해변 산책과 조개구이를 함께 즐기기 좋아요.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    hashtags: ['#인천', '#을왕리해수욕장', '#서울근교', '#노을여행', '#드라이브'],
  },
  {
    id: 'rec-027',
    region: '인천',
    location: '인천 차이나타운',
    placeName: '차이나타운 & 개항장',
    title: '인천 개항장 레트로 거리 산책',
    description: '벽화와 레트로 간판이 가득한 개항장 일대. 차이나타운에서 짜장면 한 그릇까지 챙겨 먹기 좋은 코스입니다.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=800&q=80',
    hashtags: ['#인천', '#차이나타운', '#개항장', '#레트로여행', '#당일치기'],
  },
  {
    id: 'rec-028',
    region: '대구',
    location: '대구 동성로',
    placeName: '동성로 거리',
    title: '동성로 쇼핑 & 야식 투어',
    description: '대구의 번화가 동성로. 쇼핑 후에는 야시장 골목에서 야식까지 해결할 수 있는 올인원 코스.',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80',
    hashtags: ['#대구', '#동성로', '#야시장', '#쇼핑거리', '#야식투어'],
  },
  {
    id: 'rec-029',
    region: '대구',
    location: '대구 앞산',
    placeName: '앞산전망대',
    title: '앞산 케이블카로 즐기는 도심 뷰',
    description: '앞산 케이블카를 타고 올라가면 대구 도심이 한눈에 내려다보이는 전망대를 만날 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=800&q=80',
    hashtags: ['#대구', '#앞산', '#케이블카', '#전망대', '#도심야경'],
  },
  {
    id: 'rec-030',
    region: '광주',
    location: '광주 양림동',
    placeName: '양림동 펭귄마을',
    title: '양림동 펭귄마을 레트로 골목',
    description: '버려진 물건들로 꾸며진 레트로 골목과 감각적인 카페들이 모여 있는 양림동. 사진 찍기 좋은 소도시 감성 스팟.',
    image: 'https://images.unsplash.com/photo-1526481280695-3c687fd543c0?w=800&q=80',
    hashtags: ['#광주', '#양림동', '#펭귄마을', '#레트로골목', '#사진여행'],
  },
  {
    id: 'rec-031',
    region: '광주',
    location: '광주 무등산',
    placeName: '무등산 국립공원',
    title: '무등산 억새 평원 산책',
    description: '가벼운 등산 후 억새 평원에 도착하면 광주 도심과 산 능선이 한 번에 펼쳐집니다.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=800&q=80',
    hashtags: ['#광주', '#무등산', '#억새', '#등산코스', '#뷰맛집'],
  },
  {
    id: 'rec-032',
    region: '대전',
    location: '대전 유성',
    placeName: '유성 온천 지구',
    title: '대전 유성 온천&카페 골목',
    description: '온천 호텔과 카페, 맛집이 모여 있는 유성 지구. 가볍게 온천과 산책을 함께 즐길 수 있는 휴식 코스입니다.',
    image: 'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?w=800&q=80',
    hashtags: ['#대전', '#유성온천', '#호캉스', '#카페거리', '#힐링여행'],
  },
  {
    id: 'rec-033',
    region: '대전',
    location: '대전 한밭수목원',
    placeName: '한밭수목원',
    title: '도심 속 숲, 한밭수목원 산책',
    description: '도심 한가운데에서 사계절 식물을 만날 수 있는 수목원. 가족 나들이나 산책 코스로 부담 없이 다녀오기 좋아요.',
    image: 'https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800&q=80',
    hashtags: ['#대전', '#한밭수목원', '#도심공원', '#산책코스', '#가족여행'],
  },
  {
    id: 'rec-034',
    region: '울산',
    location: '울산 대왕암공원',
    placeName: '대왕암 해안 산책로',
    title: '소나무 숲과 바다가 함께하는 대왕암',
    description: '짙은 소나무 숲길을 따라 걷다 보면 바위 사이로 부서지는 파도가 보이는 해안 산책로를 만날 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800&q=80',
    hashtags: ['#울산', '#대왕암공원', '#해안산책', '#소나무숲', '#가족코스'],
  },
  {
    id: 'rec-035',
    region: '울산',
    location: '울산 간절곶',
    placeName: '간절곶',
    title: '해돋이 명소, 간절곶 일출',
    description: '새해 첫 해를 보러 많이 찾는 간절곶. 탁 트인 바다 horizon에서 떠오르는 일출이 인상적입니다.',
    image: 'https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800&q=80',
    hashtags: ['#울산', '#간절곶', '#일출명소', '#새해여행', '#동해바다'],
  },
  {
    id: 'rec-036',
    region: '수원',
    location: '수원 화성',
    placeName: '수원 화성 행궁',
    title: '성곽 돌면서 즐기는 수원 야경',
    description: '성곽을 따라 조명이 켜지는 밤 시간이 특히 예쁜 수원 화성. 행궁과 통닭골목까지 한 번에 즐길 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1526481280695-3c687fd543c0?w=800&q=80',
    hashtags: ['#수원', '#수원화성', '#행궁', '#야경산책', '#통닭골목'],
  },
  {
    id: 'rec-037',
    region: '용인',
    location: '용인 에버랜드',
    placeName: '에버랜드',
    title: '에버랜드 튤립·장미 축제',
    description: '계절마다 달라지는 꽃 축제와 놀이기구를 함께 즐길 수 있는 테마파크. 야간 퍼레이드까지 보고 나면 하루가 금방 갑니다.',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80',
    hashtags: ['#용인', '#에버랜드', '#꽃축제', '#놀이공원', '#가족여행'],
  },
  {
    id: 'rec-038',
    region: '성남',
    location: '성남 분당',
    placeName: '율동공원',
    title: '호수공원 산책과 카페 거리',
    description: '넓은 호수와 잔디광장이 있는 공원. 주변 카페와 맛집이 잘 모여 있어 주말 나들이로 인기 많습니다.',
    image: 'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?w=800&q=80',
    hashtags: ['#분당', '#율동공원', '#호수공원', '#카페거리', '#아이와함께'],
  },
  {
    id: 'rec-039',
    region: '고양',
    location: '고양 일산',
    placeName: '호수공원',
    title: '일산 호수공원 플라워마켓',
    description: '봄·가을마다 열리는 플라워마켓과 함께 산책하기 좋은 호수공원. 가족·반려견과 함께 걷기 좋은 코스입니다.',
    image: 'https://images.unsplash.com/photo-1492496913980-501348b61469?w=800&q=80',
    hashtags: ['#일산', '#호수공원', '#플라워마켓', '#반려견동반', '#주말소풍'],
  },
  {
    id: 'rec-040',
    region: '부천',
    location: '부천 원미산',
    placeName: '원미산 진달래동산',
    title: '분홍빛으로 물드는 원미산 진달래',
    description: '봄이 되면 진달래가 산 전체를 덮는 원미산. 계단을 조금만 오르면 분홍빛 물결을 한눈에 볼 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1492496913980-501348b61469?w=800&q=80',
    hashtags: ['#부천', '#원미산', '#진달래축제', '#봄꽃여행', '#근교산책'],
  },
  {
    id: 'rec-041',
    region: '포항',
    location: '포항 영일대',
    placeName: '영일대해수욕장',
    title: '포항 영일대 해변과 스카이워크',
    description: '바다 위로 길게 뻗은 스카이워크에서 바다를 내려다볼 수 있는 영일대. 야간 조명도 예쁜 편입니다.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    hashtags: ['#포항', '#영일대해수욕장', '#스카이워크', '#동해바다', '#야간산책'],
  },
  {
    id: 'rec-042',
    region: '창원',
    location: '창원 마산',
    placeName: '가포해양공원',
    title: '마산만을 내려다보는 해양공원',
    description: '바다 전망대와 산책로가 어우러진 공원. 석양이 질 때쯤 방문하면 고즈넉한 항구 도시 분위기를 느낄 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
    hashtags: ['#창원', '#마산', '#가포해양공원', '#항구도시', '#노을뷰'],
  },
  {
    id: 'rec-043',
    region: '광양',
    location: '광양 매화마을',
    placeName: '매화마을',
    title: '봄을 알리는 광양 매화축제',
    description: '섬진강을 따라 펼쳐지는 매화 군락지. 하얀 매화꽃 사이로 보이는 강과 산이 봄 분위기를 물씬 풍깁니다.',
    image: 'https://images.unsplash.com/photo-1492496913980-501348b61469?w=800&q=80',
    hashtags: ['#광양', '#매화축제', '#봄꽃여행', '#섬진강', '#꽃구경'],
  },
  {
    id: 'rec-044',
    region: '진해',
    location: '창원 진해',
    placeName: '경화역 벚꽃길',
    title: '기찻길 따라 걷는 진해 벚꽃',
    description: '기찻길 위를 뒤덮는 벚꽃 터널로 유명한 경화역. 벚꽃 시즌에는 인파가 많지만 한 번쯤 가볼 만한 명소입니다.',
    image: 'https://images.unsplash.com/photo-1492496913980-501348b61469?w=800&q=80',
    hashtags: ['#진해', '#경화역', '#벚꽃명소', '#봄여행', '#사진스팟'],
  },
  {
    id: 'rec-045',
    region: '춘천',
    location: '춘천 남이섬',
    placeName: '남이섬',
    title: '남이섬 자전거 & 메타세쿼이아길',
    description: '강 위 섬 전체가 공원처럼 꾸며진 남이섬. 나무 터널을 자전거로 지나가며 사계절 다른 풍경을 즐길 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0?w=800&q=80',
    hashtags: ['#춘천', '#남이섬', '#자전거여행', '#메타세쿼이아길', '#가족나들이'],
  },
  {
    id: 'rec-046',
    region: '가평',
    location: '가평',
    placeName: '아침고요수목원',
    title: '사계절 정원이 아름다운 아침고요수목원',
    description: '꽃과 나무가 가득한 정원 산책 코스. 겨울 별빛 정원전에는 야간 조명까지 더해져 또 다른 분위기를 느낄 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?w=800&q=80',
    hashtags: ['#가평', '#아침고요수목원', '#정원산책', '#별빛정원전', '#데이트코스'],
  },
  {
    id: 'rec-047',
    region: '평창',
    location: '평창 대관령',
    placeName: '대관령 양떼목장',
    title: '초원 위를 걷는 대관령 양떼목장',
    description: '푸른 초원과 굴러가는 구름, 양들이 한가로이 풀을 뜯고 있는 풍경이 그대로 엽서 같은 장소.',
    image: 'https://images.unsplash.com/photo-1526481280695-3c687fd543c0?w=800&q=80',
    hashtags: ['#평창', '#대관령', '#양떼목장', '#초원풍경', '#힐링여행'],
  },
  {
    id: 'rec-048',
    region: '태안',
    location: '태안 안면도',
    placeName: '꽃지해수욕장',
    title: '석양이 아름다운 꽃지해수욕장',
    description: '서해안 노을 맛집으로 유명한 꽃지해수욕장. 할미·할아비 바위 실루엣과 함께 사진 남기기 좋습니다.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    hashtags: ['#태안', '#꽃지해수욕장', '#서해노을', '#안면도', '#드라이브코스'],
  },
  {
    id: 'rec-049',
    region: '남해',
    location: '경남 남해',
    placeName: '독일마을 & 원예예술촌',
    title: '남해 바다와 어우러진 독일마을',
    description: '형형색색 지붕이 이국적인 독일마을과 꽃이 가득한 원예예술촌까지 함께 돌아볼 수 있는 코스.',
    image: 'https://images.unsplash.com/photo-1526481280695-3c687fd543c0?w=800&q=80',
    hashtags: ['#남해', '#독일마을', '#원예예술촌', '#남해바다', '#감성여행'],
  },
  {
    id: 'rec-050',
    region: '통영',
    location: '통영 동피랑',
    placeName: '동피랑 벽화마을',
    title: '언덕 위 동피랑 벽화 골목',
    description: '파란 바다를 내려다보는 언덕 위 벽화마을. 골목마다 다른 그림과 카페들이 숨어 있어 천천히 걷기 좋습니다.',
    image: 'https://images.unsplash.com/photo-1549893075-7e95b0c0d48b?w=800&q=80',
    hashtags: ['#통영', '#동피랑', '#벽화마을', '#남해여행', '#골목산책'],
  },
];

